import Head from "next/head";
import {RegisterForm} from "../../components/RegisterForm";
export default function login() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RegisterForm />
    </div>
  );
}